export const ROLE = {
  SHOP_MANAGER: 'SHOP_MANAGER',
  WAREHOUSE_OFFICER: 'WAREHOUSE_OFFICER',
};

export const STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  DELIVERED: 'DELIVERED',
};

export const LOCATION = {
  SHOP: 'SHOP',
  WAREHOUSE: 'WAREHOUSE',
};
